### ISSUE TITLE
Change order of resources on the signature search page

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/drugmonizome-issues#40]
![image](https://user-images.githubusercontent.com/12749033/107597087-a1236180-6be7-11eb-98d7-d7f11bc14b4b.png)

**Comment by jeevangelista** [comment]
@AviMaayan  CREEDS and KinomeScan are not in here, should I put them last?
PharmGKB	1
PubChem	2
SIDER	3
STITCH	4
RDKit	5
Drugbank	6
DrugCentral	7
Drug Repurposing Hub	8
Geneshot	9
L1000FWD	10
ATC Classification System	11
KINOMEscan	
CREEDS

**Comment by AviMaayan** [comment]
In the middle? :)

**Comment by jeevangelista** [comment]
Added a priority field for resources in the schemas
