### ISSUE TITLE
Add table view for these results pages

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/drugmonizome-issues#42]
![image](https://user-images.githubusercontent.com/12749033/107597212-fbbcbd80-6be7-11eb-9a7e-d5a2cd1ea2b6.png)
It is important to provide the users with tables that contain all info.

**Comment by jeevangelista** [comment]
Should we still keep this?
<img width="1087" alt="Screen Shot 2021-02-11 at 10 44 19 AM" src="https://user-images.githubusercontent.com/1305807/107660296-1b8aca80-6c56-11eb-8418-ce5f316bad0a.png">

**Comment by AviMaayan** [comment]
Can we keep it and just bring back the table icon that you had before near the bar chart and scatter plot icons?
