### ISSUE TITLE
Add Terms of Usage to the site.

### ISSUE THREAD

**Issue by AviMaayan** [MaayanLab/drugmonizome-issues#49]
This document was reviewed:
https://docs.google.com/document/d/14oNMYh5RgKbExnmW90EInB5yi0lHqFWAwo2tdl5r_5w/edit?usp=sharing

**Comment by jeevangelista** [comment]
<img width="978" alt="Screen Shot 2021-02-16 at 1 41 31 PM" src="https://user-images.githubusercontent.com/1305807/108107033-b0c5fe80-705c-11eb-95f8-f6992744761a.png">
