### ISSUE TITLE
Result download button text needs to be changed

### ISSUE THREAD

**Issue by ekropiwnicki** [MaayanLab/drugmonizome-issues#51]
The current text states "Download Download as TSV/JSON", however, the text should be replaced with something like "Download Results as TSV/JSON"
<img width="1361" alt="Screen Shot 2021-02-16 at 3 20 30 PM" src="https://user-images.githubusercontent.com/45180650/108117209-998e0d80-706a-11eb-8bf2-89a7459bcd60.png">

**Comment by jeevangelista** [comment]
Fixed. Deploying now
